apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: freeverseio/laos-indexer:{{ .Values.imageTag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: '1'
            limits:
              memory: "2Gi"
              cpu: '2'
          env:
            - name: DB_NAME
              value: {{ .Values.postgresDb }}
            - name: DB_PORT
              value: {{ .Values.postgresPort | quote }}
            - name: DB_HOST
              value: {{ .Values.postgresDbHost }}
            - name: DB_PASS
              value: {{ .Values.postgresPassword }}
            - name: DB_USER
              value: {{ .Values.postgresUser }}
            - name: GATEWAY_ENDPOINT
              value: {{ .Values.gatewayEndpoint }}
            - name: PRIVATE_IPFS_GATEWAY
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: indexerIpfsGateway
            - name: RPC_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: {{ .Values.rpcEndpointSecretKey | quote }}
            - name: RPC_LAOS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: indexerLaosRpcEndpoint
            - name: LAOS_GLOBAL_CONSENSUS
              value: {{ .Values.laosGlobalConsensus | quote }}
            - name: LAOS_PARACHAIN
              value: {{ .Values.laosParachain | quote }}
            - name: LAOS_PALLET_INSTANCE
              value: {{ .Values.laosPalletInstance | quote }}
            - name: STARTING_BLOCK_LAOS
              value: {{ .Values.startingBlockLaos | quote }}
            - name: STARTING_BLOCK_OWNERSHIP
              value: {{ .Values.startingBlockOwnership | quote }}
          command: ["sqd", {{ .Values.command }}]
